### ISSUE TITLE
jumpgate identity token is not secure

### ISSUE THREAD

**Issue by bodenr** [softlayer/jumpgate#21]
Based on what I'm seeing right now, the token generated by the jumpgate layer is unsecure as it contains the plain text SL username and API token...

Source is here: https://github.com/softlayer/jumpgate/blob/master/jumpgate/common/sl/auth.py#L26

This results in a plan text token as `my_sl_username:my_sl_api_key`... Although this is transferred over the wire via HTTP headers and should be via SSL, many of the openstack clients will use that token in an API call to validate the token with the identity service like this: `GET http://host:port/vX.Y/tokens/{token}`. As such the {token} in that URI is the plain text SL user id and API key which can be intercepted by unauthorized parties over the wire.

IMHO -- this is not secure and the token generated by jumpgate should not have any plain text credential info.

**Comment by sudorandom** [comment]
While it's true that the hostname part of a URL is typically transmitted un-encrypted via DNS, the path part of the URL should not be. For HTTPS, the TLS encryption happens before any HTTP requests happen[1].

As for using the username/api token as the actual auth token, I agree. It's not optimal at all but in order to avoid Jumpgate itself from having state, this is something I believe should ultimately be fixed in the SoftLayer API. As far as I know there's not currently a way to request an expiring API token from the SoftLayer API. Jumpgate itself could mimic this behavior but one self-enforced requirement of Jumpgate (or at least the SoftLayer driver for it) is to be as stateless as possible. That said, having a secret key as part of the Jumpgate configuration that's used to encrypt  tokens doesn't sound like a bad idea.

Thanks for bringing this issue up. This kind of introspection will probably help this project mature.

[1] - http://stackoverflow.com/a/499594/74375.

**Comment by bodenr** [comment]
thanks for the prompt response...
+1 for the secret key mitigation.
