### ISSUE TITLE
jumpgate compute flavor 'disk' better maps to 'OS-FLV-EXT-DATA:ephemeral'

### ISSUE THREAD

**Issue by bodenr** [softlayer/jumpgate#27]
I was munking with jumpgate + novaclient and creating some CCIs based on the flavors provided by the jumpgate support.

Based on what I'm seeing, the CCIs created via jumpgate are always created with LOCAL storage in SL... So for example:

```
nova boot --flavor 2 --image MY_STANDARD_IMAGE_ID --availability-zone wdc01
```

I will get a CCI with LOCAL storage. Best I can tell SAN storage is not an option via jumpgate, but maybe I missed it.

Based on the OpenStack constructs, IMHO the flavors returned by jumpgate should use `OS-FLV-EXT-DATA:ephemeral` rather than `disk` as they do now (for [ex](https://github.com/softlayer/jumpgate/blob/master/jumpgate/compute/drivers/sl/flavors.py#L8)).

`OS-FLV-EXT-DATA:ephemeral` in a nova openstack world signifies the storage is LOCAL. Some existing openstack code in fact checks for `flavor.ephemeral` using the [novaclient flavor manager](https://github.com/openstack/python-novaclient/blob/master/novaclient/v1_1/flavors.py#L34). Also see here: http://docs.openstack.org/user-guide-admin/content/dashboard_manage_flavors.html

For example here's some [openstack trove code](https://github.com/openstack/trove/blob/master/trove/instance/models.py#L470) which expects if local disk is being used that its returned as ephemeral. I know you do not support trove per say, but I wanted to provide an example of how existing code expects the openstack constructs to be followed.

Thanks

**Comment by sudorandom** [comment]
I think you're right about local disks (SL) being comparable to ephemeral disks (OS). The only thing that doesn't match is "Ephemeral disks are not included in any snapshots.". That's not true for SL, as far as I know. Do you think SAN disks would map better to 'disk'?

My plan now is to basically double the amount of flavors, one half SAN disks and the other half local disks. Personally, I wish that [this effort](https://blueprints.launchpad.net/nova/+spec/no-flavors) would make progress towards being implemented in Nova. The issue I see is that currently running CCIs (not created by Jumpgate) will need to be mapped to a flavor. Currently there are several options besides waiting:
1. Hard-code flavors with common configurations. Return a fake flavor (that returns zero of 'unknown' for every value)  for configurations which don't match this list of flavors.
2. Add a concept of flavors to the SoftLayer API and leverage that, so those kinds of decisions don't have to be made here.
3. Generate and maintain an exhaustive list of flavors with every possible option. Only show the configurations defined in solution 1 in listing calls and allow all flavors (including the hidden ones) to be detailed individually. This solves the need to map a flavor id to an instance running that flavor. Some consideration will have to be made to avoid _changing_ an existing flavor if a new configuration is added.
4. Encode all of the flavor options into the flavor id itself.  Only show configurations defined in solution 1 in listings.

Currently these are all the options that SoftLayer provides that are associated to properties of a 'flavor':

```
:.................:....................................................................................................:
:            Name : Value                                                                                              :
:.................:....................................................................................................:
:  cpus (private) : 1,2,4,8                                                                                            :
: cpus (standard) : 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16                                                             :
:          memory : 1024,2048,3072,4096,5120,6144,7168,8192,9216,10240,11264,12288,13312,14336,15360,16384,32768,49152 :
:   local disk(0) : 25,100                                                                                             :
:   local disk(2) : 25,100,150,200,300                                                                                 :
:     san disk(0) : 25,100                                                                                             :
:     san disk(2) : 10,20,25,30,40,50,75,100,125,150,175,200,250,300,350,400,500,750,1000,1500,2000                    :
:     san disk(3) : 10,20,25,30,40,50,75,100,125,150,175,200,250,300,350,400,500,750,1000,1500,2000                    :
:     san disk(4) : 10,20,25,30,40,50,75,100,125,150,175,200,250,300,350,400,500,750,1000,1500,2000                    :
:     san disk(5) : 10,20,25,30,40,50,75,100,125,150,175,200,250,300,350,400,500,750,1000,1500,2000                    :
:             nic : 10,100,1000                                                                                        :
:.................:....................................................................................................:
```

**Comment by bodenr** [comment]
after a little more digging, i'm starting to think maybe `disk` is in fact the proper conceptual mapping here (in contrary to my creation of this issue).

as i (now) understand, OpenStack flavors map as follows:
`disk` -->  the size of the boot disk in the guest.. this is LOCAL storage equivalent to the rootfs.
`ephemeral` --> the size of a secondary LOCAL disk to mount in the guest... the key here is that although this is LOCAL storage, it's a secondary raw disk.

maybe i'm misunderstanding the openstack constructs, but the above is what i gathered from [this thread](http://osdir.com/ml/openstack-cloud-computing/2012-12/msg00063.html).

WRT "dynamic instance specs" blueprint -- doesn't appear to have much activity/traction... not holding my breath for it in the Icehouse time-frame.

one possible solution here is to continue and use the `disk` attr for the CCI disk, but then add a flavor extended attribute or extra spec to indicate the type of disk it is... i.e. `SL-DISK-TYPE: LOCAL` or `SL-DISK-TYPE: SAN`... such an approach would allow you to transport details about the actual disk type in a consistent fashion.

WRT to representing all SL "flavor" combinations... my 1st thought was along the lines of your #4 above whereupon there is canned list of the common/standard flavors and the others are maintained dynamically - encoded in the id of the flavor itself... e.g. use something like base64 encode/decode to create the flavor id which itself contains the details of the flavor spec... as a poor example suppose you want to represent a SL flavor with: 2 standard CPU + 100 G local disk + 100 Mbps nic + 4 G RAM... You could use a format like `2sCPU:100GigLOCAL:100MbsNIC:4GigRAM` then base64 encode it to get the flavor id `MnNDUFU6MTAwR2lnTE9DQUw6MTAwTWJzTklDOjRHaWdSQU0=`... That base64 flavor id can then be decoded to give you back the spec string.. obviously a 1-to-1 mapping here would be important as i'm foreseeing the need to scale out jumpgate in the future and thus each jumpgate service needs to have consistent IDs in this respect.

**Comment by bodenr** [comment]
@sudorandom -- did you have a chance to digest this one? I may have some bandwidth early next week to push something if we can come to a consensus on the impl.

**Comment by sudorandom** [comment]
Sorry, I haven't responded to this yet mostly because I agreed with all of the concepts. There's only one nit-pick that I have:
- Instead of SL-DISK-TYPE, I think OS-FLV-DISK-TYPE: (SAN | LOCAL) might go along with the naming scheme for extensions with flavor attributes. Precedent: http://api.openstack.org/api-ref-compute-ext.html#os-flv-disabled. I think either way, it would be beneficial to do this in way which might one day be incorporated into Nova as an extension. I can foresee it being useful for Nova to know more about the underlying disk(s) than whether or not it's ephemeral.

I think your thoughts are well developed for this problem so I don't have any problem with you working on it. I'll let you know if I've started working on it later today or during the weekend but until then I'd assume I haven't.

In my mind there are 2 discrete tasks out of this:
- Represent SAN and local disks in the hard-coded flavor listing and take that into consideration when creating a new CCI.
- Instead of having numeric flavor ids, the ID would be based on a base64 encoding of a string representation of all of the options that comprise a flavor.
  - Generate IDs for the list of hard-coded flavors defined in https://github.com/softlayer/jumpgate/blob/a5eb395a1486ba38d52225045a66789286364742/jumpgate/compute/drivers/sl/flavors.py#L3
  - When detailing a flavor, instead of (or in addition to) looking up the flavor by id, decode the ID into each attribute and generate a name for the dynamic flavor like "1 vCPU, 1GB memory, 25GB disk, 100Mbps network" https://github.com/softlayer/jumpgate/blob/a5eb395a1486ba38d52225045a66789286364742/jumpgate/compute/drivers/sl/flavors.py#L126
  - When listing servers in nova, generate a flavor ID using the same technique used to generate the IDs in the hard-coded list. https://github.com/softlayer/jumpgate/blob/a5eb395a1486ba38d52225045a66789286364742/jumpgate/compute/drivers/sl/servers.py#L358 and https://github.com/softlayer/jumpgate/blob/a5eb395a1486ba38d52225045a66789286364742/jumpgate/compute/drivers/sl/servers.py#L420

**Comment by Neetuj** [comment]
I am working on it

**Comment by jimlindeman** [comment]
The flavors are now always using SAN and not local (to support portable-storage based volumes) and are defined in the etc/flavor_list.json, as part of the code from issue #131 .  However, that change does not address the ability to do dynamic flavor creation from an API standpoint, and it assumes the Jumpgate used to deploy the VM is the same as the one reading the flavor from the VM, or else the flavor values can be out of sync if they don't share the same etc/flavor_list.json.  If that is still a pressing issue, we will need to re-open this into the current milestones.
