### ISSUE TITLE
Issues creating a server with a specified network

### ISSUE THREAD

**Issue by ghost** [softlayer/jumpgate#40]
Having issues creating a server with a specific network. Is that supported? 

I keep getting RESP BODY: {"badRequest": {"message": "Invalid network", "code": "400"}}
I'm using the network id returned from nova net-list or neutron net-list.

**Comment by sudorandom** [comment]
Hm.. I need to think about how to better support this. Currently, only 'public' and 'private' are supported as a network[0]. The networks you see in `nova net-list` are actually your SoftLayer subnets [1]. I'm now thinking that VLANs might be more appropriate for the net-list call and instead of specifying private and public you would specify which VLAN the CCI should be placed in.

[0] - https://github.com/softlayer/jumpgate/blob/master/jumpgate/compute/drivers/sl/servers.py#L172
[1] - https://github.com/softlayer/jumpgate/blob/master/jumpgate/compute/drivers/sl/networks.py

**Comment by anasouma** [comment]
Right, neutron net-list seems to be returning correctly... a list of vlans and the subnets under them...
neutron subnet-list returns the subnets... 
I agree, it would be good to pass in the vlan to deploy to. even if there are more than one subnet in that vlan, let the system automatically pick up the subnet... 

I also just noticed that the sl cci create command line doesn't allow specifying the vlan either, I will follow on that.

**Comment by jimlindeman** [comment]
I believe this is resolved by Issue #132
