### ISSUE TITLE
Incorrect VM state when Deleting

### ISSUE THREAD

**Issue by anasouma** [softlayer/jumpgate#46]
Hi,
I'm noticing when i delete my VM, it goes to a BUILD state then to a SHUTOFF state. That Build state is confusing and probably should not be there.

Wissam

**Comment by beittenc** [comment]
Discussed with @sudorandom real quick to confirm. We'll look into it, but I'm not sure there's going to be anything we can do. Because Jumpgate is stateless, we only have point in time information about what the SoftLayer API sends back and we have to make some assumptions based upon that data. The best fit for some of those scenarios is the BUILD state, which causes confusion here. Unfortunately, if we attempted to address it here, there's a good chance we'd end up breaking state when creating a brand new instance, which would introduce another type of confusion.
