### ISSUE TITLE
Image Metadata support 

### ISSUE THREAD

**Issue by aparnapatil** [softlayer/jumpgate#51]
currently, SL image driver does not support image metadata feature. we can support this  feature by using Tags or notes fields of Block_Device_Template_Group. But there are some pros and cons of these approaches from Softlayer side. The maximun length of tag field is only 20 characters. But once set, only authorized user can edit this. however notes field do not have such limitation on size of characters but it's an editable object.

**Comment by beittenc** [comment]
I don't think using tags for this is the right solution. It's going to present limitations, which means we're going to have to continually invent or maintain workarounds in order to imitate the OpenStack functionality. That's not going to be a winning solution in the long run. Instead, we're going to open an internal issue requesting that metadata functionality be added to images on the SoftLayer side.
